-- Auto-extracted high-confidence aliases from The Food Substitutions Bible.
-- Stores alternate ingredient names only, not source prose.

delete from ingredient_aliases
where confidence_score = 0.86
  and verified = true
  and canonical_name <> ''
  and alias_name in (
  'awabi',
  'loco',
  'muttonfish',
  'ormer',
  'paua',
  'clove pepper',
  'jamaica pepper',
  'myrtle pepper',
  'pimento',
  'rocket',
  'apple pear',
  'bicarbonate of soda',
  'bay laurel',
  'laurel leaf',
  'balsam pear',
  'cowpeas',
  'southern peas',
  'chinese white cabbage pak choi',
  'pak choy',
  'cream nut',
  'para nut',
  'musk melon',
  'mandioca',
  'manioc',
  'yuca',
  'mirliton',
  'vegetable pear',
  'chinese kale',
  'gai lan',
  'jie lan',
  'kaii laan',
  'baking chocolate',
  'bitter chocolate',
  'ibarra chocolate',
  'agua de coco',
  'agua de pipa',
  'coconut juice',
  'sweet corn',
  'biscuits',
  'borlotti bean',
  'horticultural bean',
  'coffee cream',
  'table cream',
  'cumin seeds',
  'jeera',
  'sweet potato squash',
  'donut',
  'duckling',
  'green soybean',
  'aubergine',
  'nam pla',
  'nuoc nam',
  'shottsuru',
  'pasta fresca',
  'blue ginger',
  'galanga root',
  'galingale',
  'gelatin dessert mix',
  'white sugar',
  'snap beans',
  'string beans',
  'unripe papaya',
  'cobnut',
  'filbert',
  'nocciola',
  'noisette',
  'catchup',
  'catsup',
  'american lobster',
  'maine lobster',
  'renkon',
  'oleo',
  'oleomargarine',
  'marshmallow cream',
  'japanese sweet rice wine',
  'dry mustard',
  'celery cabbage',
  'chinese cabbage',
  'da bai cai',
  'hakusai',
  'wong bok',
  'rolled oats',
  'coconut sugar',
  'gur',
  'jaggery',
  'hungarian pepper',
  'spanish pepper',
  'dau miu',
  'pea leaves',
  'pea tendrils',
  'pea vines',
  'tohbyo',
  'goobers',
  'ground nuts',
  'peanut butter morsels',
  'anardana',
  'barbary fig',
  'cactus pear',
  'pepitas',
  'pussley',
  'verdolagas',
  'wild leek',
  'cos lettuce',
  'broccoli romanesco',
  'yellow turnip',
  'oyster plant',
  'white salsify',
  'dark sesame oil',
  'benne seeds',
  'sorghum syrup',
  'crema salvadorena',
  'shoyu',
  'calamari',
  'ika',
  'icing sugar',
  'powdered sugar',
  'american- style swiss cheese',
  'tandoori coloring',
  'tempe',
  'yakitori sauce',
  'husk tomato',
  'mexican green',
  'indian',
  'indian saffron',
  'yellow ginger',
  'vanilla essence',
  'swamp cabbage',
  'ash gourd',
  'dung gua',
  'jundol',
  'petha',
  'wax gourd',
  'white gourd',
  'mapuey',
  'name',
  'zahtar',
  'courgette'
);

with rows (alias_name, ingredient_id, canonical_name, language, category, confidence_score, verified) as (
  values
    ('awabi', 'abalone', 'abalone', 'en', 'protein', 0.86, true),
    ('loco', 'abalone', 'abalone', 'en', 'protein', 0.86, true),
    ('muttonfish', 'abalone', 'abalone', 'en', 'protein', 0.86, true),
    ('ormer', 'abalone', 'abalone', 'en', 'protein', 0.86, true),
    ('paua', 'abalone', 'abalone', 'en', 'protein', 0.86, true),
    ('clove pepper', 'allspice', 'allspice', 'en', 'pantry', 0.86, true),
    ('jamaica pepper', 'allspice', 'allspice', 'en', 'pantry', 0.86, true),
    ('myrtle pepper', 'allspice', 'allspice', 'en', 'pantry', 0.86, true),
    ('pimento', 'allspice', 'allspice', 'en', 'pantry', 0.86, true),
    ('rocket', 'arugula', 'arugula', 'en', 'vegetable', 0.86, true),
    ('apple pear', 'asian_pear', 'Asian pear', 'en', 'fruit', 0.86, true),
    ('bicarbonate of soda', 'baking_soda', 'baking soda', 'en', 'pantry', 0.86, true),
    ('bay laurel', 'bay_leaf', 'Bay Leaf', 'en', 'pantry', 0.86, true),
    ('laurel leaf', 'bay_leaf', 'Bay Leaf', 'en', 'pantry', 0.86, true),
    ('balsam pear', 'bitter_melon', 'Bitter Melon', 'en', 'vegetable', 0.86, true),
    ('cowpeas', 'black_eyed_peas', 'Black-Eyed Peas', 'en', 'protein', 0.86, true),
    ('southern peas', 'black_eyed_peas', 'Black-Eyed Peas', 'en', 'protein', 0.86, true),
    ('chinese white cabbage pak choi', 'bok_choy', 'bok choy', 'en', 'vegetable', 0.86, true),
    ('pak choy', 'bok_choy', 'bok choy', 'en', 'vegetable', 0.86, true),
    ('cream nut', 'brazil_nuts', 'Brazil Nuts', 'en', 'pantry', 0.86, true),
    ('para nut', 'brazil_nuts', 'Brazil Nuts', 'en', 'pantry', 0.86, true),
    ('musk melon', 'cantaloupe', 'Cantaloupe', 'en', 'fruit', 0.86, true),
    ('mandioca', 'cassava', 'Cassava', 'en', 'vegetable', 0.86, true),
    ('manioc', 'cassava', 'Cassava', 'en', 'vegetable', 0.86, true),
    ('yuca', 'cassava', 'Cassava', 'en', 'vegetable', 0.86, true),
    ('mirliton', 'chayote', 'Chayote', 'en', 'vegetable', 0.86, true),
    ('vegetable pear', 'chayote', 'Chayote', 'en', 'vegetable', 0.86, true),
    ('chinese kale', 'chinese_broccoli', 'Chinese broccoli', 'en', 'vegetable', 0.86, true),
    ('gai lan', 'chinese_broccoli', 'Chinese broccoli', 'en', 'vegetable', 0.86, true),
    ('jie lan', 'chinese_broccoli', 'Chinese broccoli', 'en', 'vegetable', 0.86, true),
    ('kaii laan', 'chinese_broccoli', 'Chinese broccoli', 'en', 'vegetable', 0.86, true),
    ('baking chocolate', 'chocolate', 'chocolate', 'en', 'pantry', 0.86, true),
    ('bitter chocolate', 'chocolate', 'chocolate', 'en', 'pantry', 0.86, true),
    ('ibarra chocolate', 'chocolate', 'chocolate', 'en', 'pantry', 0.86, true),
    ('agua de coco', 'coconut_water', 'Coconut water', 'en', 'other', 0.86, true),
    ('agua de pipa', 'coconut_water', 'Coconut water', 'en', 'other', 0.86, true),
    ('coconut juice', 'coconut_water', 'Coconut water', 'en', 'other', 0.86, true),
    ('sweet corn', 'corn', 'Corn', 'en', 'pantry', 0.86, true),
    ('biscuits', 'crackers', 'crackers', 'en', 'pantry', 0.86, true),
    ('borlotti bean', 'cranberry_beans', 'Cranberry Beans', 'en', 'protein', 0.86, true),
    ('horticultural bean', 'cranberry_beans', 'Cranberry Beans', 'en', 'protein', 0.86, true),
    ('coffee cream', 'cream_light', 'Cream light', 'en', 'dairy', 0.86, true),
    ('table cream', 'cream_light', 'Cream light', 'en', 'dairy', 0.86, true),
    ('cumin seeds', 'cumin', 'Cumin', 'en', 'pantry', 0.86, true),
    ('jeera', 'cumin', 'Cumin', 'en', 'pantry', 0.86, true),
    ('sweet potato squash', 'delicata_squash', 'Delicata Squash', 'en', 'vegetable', 0.86, true),
    ('donut', 'doughnuts', 'Doughnuts', 'en', 'grain', 0.86, true),
    ('duckling', 'duck', 'duck', 'en', 'protein', 0.86, true),
    ('green soybean', 'edamame', 'Edamame', 'en', 'protein', 0.86, true),
    ('aubergine', 'eggplant', 'eggplant', 'en', 'vegetable', 0.86, true),
    ('nam pla', 'fish_sauce', 'fish sauce', 'en', 'pantry', 0.86, true),
    ('nuoc nam', 'fish_sauce', 'fish sauce', 'en', 'pantry', 0.86, true),
    ('shottsuru', 'fish_sauce', 'fish sauce', 'en', 'pantry', 0.86, true),
    ('pasta fresca', 'fresh_pasta', 'Fresh pasta', 'en', 'grain', 0.86, true),
    ('blue ginger', 'galangal', 'Galangal', 'en', 'pantry', 0.86, true),
    ('galanga root', 'galangal', 'Galangal', 'en', 'pantry', 0.86, true),
    ('galingale', 'galangal', 'Galangal', 'en', 'pantry', 0.86, true),
    ('gelatin dessert mix', 'gelatin_flavored', 'Gelatin flavored', 'en', 'grain', 0.86, true),
    ('white sugar', 'granulated_sugar', 'granulated sugar', 'en', 'pantry', 0.86, true),
    ('snap beans', 'green_bean', 'green bean', 'en', 'vegetable', 0.86, true),
    ('string beans', 'green_bean', 'green bean', 'en', 'vegetable', 0.86, true),
    ('unripe papaya', 'green_papaya', 'green papaya', 'en', 'fruit', 0.86, true),
    ('cobnut', 'hazelnuts', 'Hazelnuts', 'en', 'pantry', 0.86, true),
    ('filbert', 'hazelnuts', 'Hazelnuts', 'en', 'pantry', 0.86, true),
    ('nocciola', 'hazelnuts', 'Hazelnuts', 'en', 'pantry', 0.86, true),
    ('noisette', 'hazelnuts', 'Hazelnuts', 'en', 'pantry', 0.86, true),
    ('catchup', 'ketchup', 'ketchup', 'en', 'pantry', 0.86, true),
    ('catsup', 'ketchup', 'ketchup', 'en', 'pantry', 0.86, true),
    ('american lobster', 'lobster', 'Lobster', 'en', 'protein', 0.86, true),
    ('maine lobster', 'lobster', 'Lobster', 'en', 'protein', 0.86, true),
    ('renkon', 'lotus_root', 'lotus root', 'en', 'vegetable', 0.86, true),
    ('oleo', 'margarine', 'Margarine', 'en', 'dairy', 0.86, true),
    ('oleomargarine', 'margarine', 'Margarine', 'en', 'dairy', 0.86, true),
    ('marshmallow cream', 'marshmallows', 'marshmallows', 'en', 'pantry', 0.86, true),
    ('japanese sweet rice wine', 'mirin', 'mirin', 'en', 'pantry', 0.86, true),
    ('dry mustard', 'mustard', 'mustard', 'en', 'pantry', 0.86, true),
    ('celery cabbage', 'napa_cabbage', 'napa cabbage', 'en', 'vegetable', 0.86, true),
    ('chinese cabbage', 'napa_cabbage', 'napa cabbage', 'en', 'vegetable', 0.86, true),
    ('da bai cai', 'napa_cabbage', 'napa cabbage', 'en', 'vegetable', 0.86, true),
    ('hakusai', 'napa_cabbage', 'napa cabbage', 'en', 'vegetable', 0.86, true),
    ('wong bok', 'napa_cabbage', 'napa cabbage', 'en', 'vegetable', 0.86, true),
    ('rolled oats', 'oat', 'oat', 'en', 'pantry', 0.86, true),
    ('coconut sugar', 'palm_sugar', 'palm sugar', 'en', 'pantry', 0.86, true),
    ('gur', 'palm_sugar', 'palm sugar', 'en', 'pantry', 0.86, true),
    ('jaggery', 'palm_sugar', 'palm sugar', 'en', 'pantry', 0.86, true),
    ('hungarian pepper', 'paprika', 'Paprika', 'en', 'pantry', 0.86, true),
    ('spanish pepper', 'paprika', 'Paprika', 'en', 'pantry', 0.86, true),
    ('dau miu', 'pea_shoots', 'pea shoots', 'en', 'vegetable', 0.86, true),
    ('pea leaves', 'pea_shoots', 'pea shoots', 'en', 'vegetable', 0.86, true),
    ('pea tendrils', 'pea_shoots', 'pea shoots', 'en', 'vegetable', 0.86, true),
    ('pea vines', 'pea_shoots', 'pea shoots', 'en', 'vegetable', 0.86, true),
    ('tohbyo', 'pea_shoots', 'pea shoots', 'en', 'vegetable', 0.86, true),
    ('goobers', 'peanut', 'peanut', 'en', 'pantry', 0.86, true),
    ('ground nuts', 'peanut', 'peanut', 'en', 'pantry', 0.86, true),
    ('peanut butter morsels', 'peanut_butter', 'peanut butter', 'en', 'pantry', 0.86, true),
    ('anardana', 'pomegranate', 'Pomegranate', 'en', 'fruit', 0.86, true),
    ('barbary fig', 'prickly_pear', 'Prickly Pear', 'en', 'fruit', 0.86, true),
    ('cactus pear', 'prickly_pear', 'Prickly Pear', 'en', 'fruit', 0.86, true),
    ('pepitas', 'pumpkin_seeds', 'Pumpkin Seeds', 'en', 'pantry', 0.86, true),
    ('pussley', 'purslane', 'Purslane', 'en', 'vegetable', 0.86, true),
    ('verdolagas', 'purslane', 'Purslane', 'en', 'vegetable', 0.86, true),
    ('wild leek', 'ramps', 'Ramps', 'en', 'vegetable', 0.86, true),
    ('cos lettuce', 'romaine_lettuce', 'romaine lettuce', 'en', 'vegetable', 0.86, true),
    ('broccoli romanesco', 'romanesco', 'Romanesco', 'en', 'vegetable', 0.86, true),
    ('yellow turnip', 'rutabaga', 'Rutabaga', 'en', 'vegetable', 0.86, true),
    ('oyster plant', 'salsify', 'Salsify', 'en', 'vegetable', 0.86, true),
    ('white salsify', 'salsify', 'Salsify', 'en', 'vegetable', 0.86, true),
    ('dark sesame oil', 'sesame_oil', 'sesame oil', 'en', 'pantry', 0.86, true),
    ('benne seeds', 'sesame_seed', 'sesame seed', 'en', 'pantry', 0.86, true),
    ('sorghum syrup', 'sorghum', 'Sorghum', 'en', 'pantry', 0.86, true),
    ('crema salvadorena', 'sour_cream', 'sour cream', 'en', 'dairy', 0.86, true),
    ('shoyu', 'soy_sauce', 'soy sauce', 'en', 'pantry', 0.86, true),
    ('calamari', 'squid', 'squid', 'en', 'protein', 0.86, true),
    ('ika', 'squid', 'squid', 'en', 'protein', 0.86, true),
    ('icing sugar', 'sugar', 'sugar', 'en', 'pantry', 0.86, true),
    ('powdered sugar', 'sugar', 'sugar', 'en', 'pantry', 0.86, true),
    ('american- style swiss cheese', 'swiss_cheese', 'Swiss Cheese', 'en', 'dairy', 0.86, true),
    ('tandoori coloring', 'tandoori_paste', 'tandoori paste', 'en', 'pantry', 0.86, true),
    ('tempe', 'tempeh', 'Tempeh', 'en', 'other', 0.86, true),
    ('yakitori sauce', 'teriyaki_sauce', 'Teriyaki sauce', 'en', 'sauce', 0.86, true),
    ('husk tomato', 'tomatillos', 'Tomatillos', 'en', 'vegetable', 0.86, true),
    ('mexican green', 'tomatillos', 'Tomatillos', 'en', 'vegetable', 0.86, true),
    ('indian', 'turmeric', 'Turmeric', 'en', 'pantry', 0.86, true),
    ('indian saffron', 'turmeric', 'Turmeric', 'en', 'pantry', 0.86, true),
    ('yellow ginger', 'turmeric', 'Turmeric', 'en', 'pantry', 0.86, true),
    ('vanilla essence', 'vanilla_extract', 'vanilla extract', 'en', 'pantry', 0.86, true),
    ('swamp cabbage', 'water_spinach', 'water spinach', 'en', 'vegetable', 0.86, true),
    ('ash gourd', 'winter_melon', 'winter melon', 'en', 'vegetable', 0.86, true),
    ('dung gua', 'winter_melon', 'winter melon', 'en', 'vegetable', 0.86, true),
    ('jundol', 'winter_melon', 'winter melon', 'en', 'vegetable', 0.86, true),
    ('petha', 'winter_melon', 'winter melon', 'en', 'vegetable', 0.86, true),
    ('wax gourd', 'winter_melon', 'winter melon', 'en', 'vegetable', 0.86, true),
    ('white gourd', 'winter_melon', 'winter melon', 'en', 'vegetable', 0.86, true),
    ('mapuey', 'yam', 'yam', 'en', 'vegetable', 0.86, true),
    ('name', 'yam', 'yam', 'en', 'vegetable', 0.86, true),
    ('zahtar', 'zaatar', 'Za''Atar', 'en', 'pantry', 0.86, true),
    ('courgette', 'zucchini', 'zucchini', 'en', 'vegetable', 0.86, true)
)
insert into ingredient_aliases (
  alias_name, ingredient_id, canonical_name, language, category, confidence_score, verified, updated_at
)
select rows.alias_name, rows.ingredient_id, rows.canonical_name, rows.language, rows.category, rows.confidence_score, rows.verified, now()
from rows
where exists (select 1 from ingredients where ingredients.ingredient_id = rows.ingredient_id)
on conflict (alias_name) do nothing;
